#!/usr/bin/env python3
"""
murlok_scraper.py — Parsea el JSON de murlok.io y genera tankBuddy/Config.lua

Uso:
    python murlok_scraper.py <archivo_murlok> [ruta_Config.lua]

Ejemplo:
    python murlok_scraper.py "C:/Users/Usuario/Desktop/codigo murlok_io" tankBuddy/Config.lua
"""

import json
import statistics
import sys
from pathlib import Path

STAT_FIELDS = {
    "haste":       ("Haste",       "HasteBonus"),
    "crit":        ("Crit",        "CritBonus"),
    "mastery":     ("Mastery",     "MasteryBonus"),
    "versatility": ("Versatility", "VersatilityBonus"),
    "avoidance":   ("Avoidance",   "AvoidanceBonus"),
    "leech":       ("Leech",       "LeechValue"),
    "speed":       ("Speed",       "SpeedBonus"),
}


def analyze(filepath):
    with open(filepath, encoding="utf-8") as f:
        data = json.load(f)

    chars = data.get("Characters", [])
    updated = data.get("UpdatedAt", "unknown")
    spec = data.get("SpecializationSlug", "unknown")

    collected = {k: {"rating": [], "bonus": []} for k in STAT_FIELDS}

    for char in chars:
        for key, (rating_field, bonus_field) in STAT_FIELDS.items():
            r = char.get(rating_field)
            b = char.get(bonus_field)
            if r is not None:
                collected[key]["rating"].append(r)
            if b is not None:
                collected[key]["bonus"].append(b)

    result = {}
    for key, vals in collected.items():
        if vals["rating"]:
            result[key] = {
                "median_rating": statistics.median(vals["rating"]),
                "median_bonus":  statistics.median(vals["bonus"]) if vals["bonus"] else 0.0,
            }

    return result, len(chars), updated, spec


def generate_config(stats, n_chars, updated_at, spec, out_path):
    total = sum(v["median_rating"] for v in stats.values())

    lines = [
        "-- Auto-generated by murlok_scraper.py — do not edit manually",
        f"-- murlok.io {spec} M+  |  {updated_at}  |  {n_chars} characters",
        "",
        "tankBuddy_Config = {",
        f'    UpdatedAt      = "{updated_at}",',
        f'    CharacterCount = {n_chars},',
        f'    Spec           = "{spec}",',
        "    Stats = {",
    ]

    for key, vals in stats.items():
        weight = vals["median_rating"] / total if total > 0 else 0
        lines.append(
            f'        {key:<12} = '
            f'{{ median_rating = {vals["median_rating"]:>6.0f},'
            f' median_bonus = {vals["median_bonus"]:>6.2f},'
            f' weight = {weight:.4f} }},'
        )

    lines += ["    },", "}"]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Config generado: {out_path}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)

    input_file  = Path(sys.argv[1])
    output_file = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("tankBuddy/Config.lua")

    stats, n_chars, updated_at, spec = analyze(input_file)

    total = sum(v["median_rating"] for v in stats.values())
    print(f"\n{spec.upper()} M+ — {n_chars} personajes ({updated_at})\n")
    print(f"{'Stat':<14} {'Median Rating':>14} {'Median %':>10} {'Weight':>8}")
    print("-" * 52)
    for key, vals in stats.items():
        w = vals["median_rating"] / total if total > 0 else 0
        print(f"{key:<14} {vals['median_rating']:>14.0f} {vals['median_bonus']:>9.1f}%  {w:.4f}")

    generate_config(stats, n_chars, updated_at, spec, output_file)
