-- Auto-generated by murlok_scraper.py — do not edit manually
-- murlok.io blood M+  |  2026-04-21T10:15:53.542481Z  |  50 characters

tankBuddy_Config = {
    UpdatedAt      = "2026-04-21T10:15:53.542481Z",
    CharacterCount = 50,
    Spec           = "blood",
    Stats = {
        haste        = { median_rating =    536, median_bonus =  12.18, weight = 0.2152 },
        crit         = { median_rating =    668, median_bonus =  14.52, weight = 0.2682 },
        mastery      = { median_rating =    606, median_bonus =  26.37, weight = 0.2435 },
        versatility  = { median_rating =    496, median_bonus =   9.19, weight = 0.1991 },
        avoidance    = { median_rating =     54, median_bonus =   1.48, weight = 0.0219 },
        leech        = { median_rating =    130, median_bonus =   3.75, weight = 0.0522 },
    },
}